version: '3.8'
services:
  payoorserver:
    container_name: payoorserver-development
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.development.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - nodeserver
      - adminui
      - chatuiserver
      - llmserver
      - services
    networks:
      - payoor_development_network      

  payoordb:
    container_name: payoordb-development
    image: mongo
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
    networks:
      - payoor_development_network  

  redisdb:
    container_name: redisdb-development
    image: redis:latest
    command: redis-server --appendonly yes --save 900 1 300 10 60 10000
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data  
    networks:
      - payoor_development_network

  nodeserver:
    container_name: nodeserver-development
    restart: always
    build: ./nodeserver
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - payoordb
    networks:
      - payoor_development_network

  adminui:
    container_name: adminui-development
    restart: always
    build: ./adminui
    networks:
      - payoor_development_network

  chatuiserver:
    container_name: chatuiserver-development
    restart: always
    build: ./chatuiserver
    networks:
      - payoor_development_network

  llmserver:
    container_name: llmserver-development
    build: ./llmserver
    restart: always
    env_file: ./llmserver/.env
    networks:
      - payoor_development_network

  services:
    container_name: services
    restart: always
    build: ./services
    networks:
      - payoor_development_network 

  errorserver:
    container_name: error-server
    restart: always
    build: ./errorlogs
    networks:
      - payoor_development_network   

networks:
  payoor_development_network:
    driver: bridge

volumes:
  redis_data: 
  mongo_data: