version: '3.8'
services:
  payoorserver:
    container_name: payoorserver
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - nodeserver
      - adminui
      - chatuiserver
    networks:
      - payoor_network
    
  payoordb:
    container_name: payoordb
    image: mongo
    environment:
      - PORT=27017
    volumes:
      - /data-vol:/data/payoordb
    networks:
      - payoor_network

  nodeserver:
    container_name: nodeserver
    restart: always
    build: ./nodeserver
    environment:
      - PORT=8080
      - NODE_ENV=production
    depends_on:
      - payoordb
    networks:
      - payoor_network

  adminui:
    container_name: adminui
    restart: always
    build: ./adminui
    environment:
      - PORT=8082
      - NODE_ENV=production
    networks:
      - payoor_network

  chatuiserver:
    container_name: chatuiserver
    restart: always
    build: ./chatuiserver
    environment:
      - PORT=8083
      - NODE_ENV=production
    networks:
      - payoor_network

networks:
  payoor_network:
    driver: bridge