version: '3.8'
services:
  payoorserver:
    container_name: payoorserver-development
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.development.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - nodeserver
      - adminui
      - chatuiserver
    networks:
      - payoor_development_network
    
  payoordb:
    container_name: payoordb-development
    image: mongo
    environment:
      - PORT=27017
    volumes:
      - /data-vol-development:/data/payoordb
    networks:
      - payoor_development_network

  nodeserver:
    container_name: nodeserver-development
    restart: always
    build: ./nodeserver
    environment:
      - PORT=8080
      - NODE_ENV=development
    depends_on:
      - payoordb
    networks:
      - payoor_development_network

  adminui:
    container_name: adminui-development
    restart: always
    build: ./adminui
    environment:
      - PORT=8082
      - NODE_ENV=development
    networks:
      - payoor_development_network

  chatuiserver:
    container_name: chatuiserver-development
    restart: always
    build: ./chatuiserver
    environment:
      - PORT=8083
      - NODE_ENV=development
    networks:
      - payoor_development_network

networks:
  payoor_development_network:
    driver: bridge