nigeria_groceries = """
  "Garri (white)",
  "Garri (yellow)",
  "Rice (local)",
  "Rice (imported)",
  "Yam tubers",
  "Plantains",
  "Palm oil",
  "Groundnut oil",
  "Tomatoes (fresh)",
  "Onions (red)",
  "Scotch bonnet peppers (ata rodo)",
  "Bell peppers (tatashe)",
  "Egusi seeds",
  "Beans (brown)",
  "Beans (black-eyed)",
  "Sweet potatoes",
  "Irish potatoes",
  "Cassava flour",
  "Semolina",
  "Wheat flour",
  "Ground crayfish",
  "Dried fish",
  "Stock fish (okporoko)",
  "Beef",
  "Goat meat",
  "Chicken",
  "Turkey",
  "Smoked fish",
  "Snails",
  "Palm kernel oil",
  "Coconut oil",
  "Ogbono seeds",
  "Okra (fresh)",
  "Okra (dried)",
  "Bitter leaf",
  "Pumpkin leaves (ugwu)",
  "Water leaf",
  "Scent leaves",
  "Curry leaves",
  "Bay leaves",
  "Locust beans (iru)",
  "Ground pepper",
  "Cameroon pepper",
  "Black pepper",
  "Ginger (fresh)",
  "Garlic",
  "Turmeric",
  "Nutmeg",
  "Maggi cubes",
  "Knorr cubes",
  "Salt",
  "Sugar",
  "Honey",
  "Coconut (fresh)",
  "Coconut (dried)",
  "Groundnuts (raw)",
  "Groundnuts (roasted)",
  "Tiger nuts (aki hausa)",
  "Cola nuts",
  "Garden eggs",
  "African cucumber",
  "Carrots",
  "Cabbage",
  "Lettuce",
  "Spring onions",
  "Green peas",
  "Green beans",
  "Corn (fresh)",
  "Corn flour",
  "Millet",
  "Sorghum",
  "Guinea corn",
  "Bambara nuts",
  "African yam beans",
  "Cowpea",
  "Breadfruit",
  "African breadnut",
  "African pear",
  "Soursop",
  "Pawpaw",
  "Mango",
  "Orange",
  "Lime",
  "Lemon",
  "Banana",
  "Guava",
  "Cashew fruit",
  "African star apple (agbalumo)",
  "African cherry (agbalumo)",
  "Tamarind",
  "Date palm fruit",
  "Zobo leaves",
  "Moringa leaves",
  "Uziza leaves",
  "Utazi leaves",
  "Nchanwu leaves",
  "Ehuru seeds",
  "Alligator pepper",
  "Grains of paradise",
  "African nutmeg",
  "African basil",
  "Thyme",
  "Rosemary",
  "Curry powder",
  "Fish powder",
  "Suya spice",
  "Yaji spice",
  "Achu spice",
  "Palm kernel",
  "Bamboo shoots",
  "Water yam",
  "Aerial yam",
  "Yellow yam",
  "Cocoyam",
  "African eggplant",
  "African spinach",
  "Jute leaves",
  "Bush mango",
  "Bush pear",
  "African walnut",
  "African apple",
  "African plum",
  "Baobab fruit",
  "Baobab leaves",
  "Miracle fruit",
  "Prekese",
  "Dawadawa",
  "Shea butter",
  "Palm nuts",
  "Kola nuts",
  "Bitter kola",
  "Alligator pepper pods",
  "African licorice",
  "African mint",
  "African thyme",
  "African oregano",
  "Waterleaf",
  "Nigerian basil",
  "Uziza seeds",
  "Ehuru pods",
  "African cardamom",
  "Bush pepper",
  "Guinea pepper",
  "African black pepper",
  "African ginger",
  "Wild mushrooms",
  "Termites (edible)",
  "Palm weevil larvae",
  "Catfish (fresh)",
  "Tilapia (fresh)",
  "Mackerel (fresh)",
  "Sardines (fresh)",
  "Croaker fish",
  "Barracuda",
  "Red snapper",
  "Dried shrimp",
  "Periwinkles",
  "African giant snails",
  "Cow skin (ponmo)",
  "Tripe",
  "Cow feet",
  "Goat head",
  "Chicken feet",
  "Turkey wings",
  "Guinea fowl",
  "Quail eggs",
  "Duck eggs",
  "Local chicken eggs",
  "Palm wine",
  "Zobo drink",
  "Kunu drink",
  "Fura powder",
  "Pap (akamu)",
  "Custard powder",
  "Peak milk powder",
  "Three Crowns milk",
  "Milo",
  "Bournvita",
  "Ovaltine",
  "Tea leaves",
  "Coffee (instant)",
  "Bread (local)",
  "Bread (sliced)",
  "Crackers",
  "Cabin biscuits",
  "Coconut biscuits",
  "Plantain chips",
  "Yam chips",
  "Cassava chips",
  "Groundnut cake (kulikuli)",
  "Coconut candy",
  "Tiger nut milk",
  "Soybean milk",
  "Powdered pepper soup spice",
  "Dried okra powder",
  "Dried bitter leaf powder",
  "Dried uziza powder",
  "Dried ehuru powder",
  "Ground ogbono",
  "Ground egusi",
  "Ground crayfish",
  "Ground dried shrimp",
  "Ground dried fish",
  "Ground melon seeds",
  "Ground pumpkin seeds",
  "Ground sesame seeds",
  "Ground tiger nuts",
  "Ground bambara nuts",
  "Cornflakes",
  "Golden Morn",
  "Indomie noodles",
  "Spaghetti",
  "Macaroni",
  "Couscous",
  "Popcorn",
  "Groundnut oil (local)",
  "Groundnut oil (refined)",
  "Vegetable oil",
  "Soybean oil",
  "Coconut milk",
  "Tomato paste",
  "Tomato puree",
  "Dried tomatoes",
  "Dried onions",
  "Dried garlic",
  "Dried ginger",
  "Dried mushrooms",
  "Dried bitter leaf",
  "Dried uziza leaf",
  "Dried scent leaf",
  "Dried mint leaf",
  "Dried bay leaf",
  "Dried curry leaf",
  "Dried thyme",
  "Dried rosemary",
  "Dried basil",
  "Dried oregano",
  "Palm kernel cake",
  "Groundnut cake",
  "Soybean cake",
  "Coconut cake",
  "Rice bran",
  "Wheat bran",
  "Corn bran",
  "Millet bran",
  "Sorghum bran",
  "Guinea corn bran",
  "Cassava starch",
  "Corn starch",
  "Potato starch",
  "Arrowroot starch",
  "Tapioca pearls",
  "Sago pearls",
  "Pearl barley",
  "Split peas",
  "Red lentils",
  "Green lentils",
  "Brown lentils",
  "Black lentils",
  "Chickpeas",
  "Black beans",
  "Kidney beans",
  "Lima beans",
  "Navy beans",
  "Pinto beans",
  "Fava beans",
  "Mung beans",
  "Adzuki beans",
  "Soybeans",
  "White rice (local)",
  "White rice (imported)",
  "Brown rice",
  "Basmati rice",
  "Jasmine rice",
  "Wild rice",
  "Black rice",
  "Red rice",
  "Parboiled rice",
  "Broken rice",
  "Rice flour",
  "Rice bran oil",
  "Rice vinegar",
  "Rice wine",
  "Rice noodles",
  "Rice paper",
  "Rice crackers",
  "Rice cakes",
  "Rice pudding mix",
  "Rice milk",
  "White garri",
  "Yellow garri",
  "Red garri",
  "Ijebu garri",
  "Garri oloyin",
  "Garri Edo",
  "Garri Igbo",
  "Garri Yoruba",
  "Fine garri",
  "Coarse garri",
  "Cassava flour (white)",
  "Cassava flour (yellow)",
  "Cassava starch",
  "Cassava flakes",
  "Cassava chips",
  "Cassava pellets",
  "Cassava granules",
  "Cassava bread",
  "Cassava crackers",
  "Cassava cookies",
  "White yam flour",
  "Yellow yam flour",
  "Water yam flour",
  "Aerial yam flour",
  "Bitter yam flour",
  "Chinese yam flour",
  "Wild yam flour",
  "Yam flakes",
  "Yam chips",
  "Yam crackers",
  "Plantain flour",
  "Plantain chips",
  "Plantain crackers",
  "Plantain cookies",
  "Ripe plantains",
  "Green plantains",
  "Cooking bananas",
  "Sweet bananas",
  "Lady finger bananas",
  "Red bananas",
  "Guinea fowl eggs",
  "Duck eggs",
  "Turkey eggs",
  "Quail eggs",
  "Local chicken eggs",
  "Guinea fowl meat",
  "Duck meat",
  "Turkey meat",
  "Quail meat",
  "Local chicken meat",
  "Guinea fowl liver",
  "Duck liver",
  "Turkey liver",
  "Quail liver",
  "Chicken liver",
  "Guinea fowl gizzard",
  "Duck gizzard",
  "Turkey gizzard",
  "Quail gizzard",
  "Chicken gizzard",
  "Fresh beef",
  "Dried beef",
  "Smoked beef",
  "Ground beef",
  "Beef liver",
  "Beef heart",
  "Beef kidney",
  "Beef tripe",
  "Beef tongue",
  "Beef oxtail",
  "Fresh goat meat",
  "Dried goat meat",
  "Smoked goat meat",
  "Ground goat meat",
  "Goat liver",
  "Goat heart",
  "Goat kidney",
  "Goat tripe",
  "Goat head",
  "Goat feet",
  "Fresh lamb meat",
  "Dried lamb meat",
  "Smoked lamb meat",
  "Ground lamb meat",
  "Lamb liver",
  "Lamb heart",
  "Lamb kidney",
  "Lamb tripe",
  "Lamb head",
  "Lamb feet",
  "Fresh pork",
  "Dried pork",
  "Smoked pork",
  "Ground pork",
  "Pork liver",
  "Pork heart",
  "Pork kidney",
  "Pork tripe",
  "Pork head",
  "Pork feet",
  "Fresh fish (tilapia)",
  "Fresh fish (catfish)",
  "Fresh fish (mackerel)",
  "Fresh fish (croaker)",
  "Fresh fish (snapper)",
  "Dried fish (cod)",
  "Dried fish (stockfish)",
  "Dried fish (mackerel)",
  "Dried fish (herring)",
  "Dried fish (sardines)",
  "Smoked fish (catfish)",
  "Smoked fish (mackerel)",
  "Smoked fish (herring)",
  "Smoked fish (tilapia)",
  "Smoked fish (croaker)",
  "Fresh shrimp",
  "Dried shrimp",
  "Smoked shrimp",
  "Ground shrimp",
  "Shrimp powder",
  "Fresh crab",
  "Dried crab",
  "Smoked crab",
  "Ground crab",
  "Crab powder",
  "Fresh snails",
  "Dried snails",
  "Smoked snails",
  "Ground snails",
  "Snail powder",
  "Fresh periwinkles",
  "Dried periwinkles",
  "Smoked periwinkles",
  "Ground periwinkles",
  "Periwinkle powder",
  "Fresh crayfish",
  "Dried crayfish",
  "Smoked crayfish",
  "Ground crayfish",
  "Crayfish powder",
  "Fresh lobster",
  "Dried lobster",
  "Smoked lobster",
  "Ground lobster",
  "Lobster powder",
  "Fresh prawns",
  "Dried prawns",
  "Smoked prawns",
  "Ground prawns",
  "Prawn powder",
  "Fresh oysters",
  "Dried oysters",
  "Smoked oysters",
  "Ground oysters",
  "Oyster powder",
  "Fresh mussels",
  "Dried mussels",
  "Smoked mussels",
  "Ground mussels",
  "Mussel powder",
  "Fresh clams",
  "Dried clams",
  "Smoked clams",
  "Ground clams",
  "Clam powder",
  "Fresh scallops",
  "Dried scallops",
  "Smoked scallops",
  "Ground scallops",
  "Scallop powder",
  "Fresh squid",
  "Dried squid",
  "Smoked squid",
  "Ground squid",
  "Squid powder",
  "Fresh octopus",
  "Dried octopus",
  "Smoked octopus",
  "Ground octopus",
  "Octopus powder",
  "Fresh cuttle fish",
  "Dried cuttle fish",
  "Smoked cuttle fish",
  "Ground cuttle fish",
  "Cuttle fish powder",
  "Fresh sea cucumber",
  "Dried sea cucumber",
  "Smoked sea cucumber",
  "Ground sea cucumber",
  "Sea cucumber powder",
  "Fresh sea urchin",
  "Dried sea urchin",
  "Smoked sea urchin",
  "Ground sea urchin",
  "Sea urchin powder",
  "Fresh abalone",
  "Dried abalone",
  "Smoked abalone",
  "Ground abalone",
  "Abalone powder",
  "Fresh conch",
  "Dried conch",
  "Smoked conch",
  "Ground conch",
  "Conch powder",
  "Fresh whelk",
  "Dried whelk",
  "Smoked whelk"
"""